### PR TITLE
Limit the number of selectable images

### PR DESCRIPTION
**Pull request by mjrehder**
Added feature to limit the total number of selectable images in order to control how many images the user can select at a time.

### CODE REVIEW

**Comment by davbeck** [comment]
I'm not sure about this one. On the one hand, if developers don't use the property, it won't change anything. However, I have some UX concerns around this. From looking at the code, when the user has hit the max number of photos, selection just stops working, which would seem to user's to be a bug.

The way I've handled this situation in my own app is that I validate the number of photos when the user taps the next button and show an alert if they have more than the maximum. But even that experience could be approved since a user could spend a good amount of time selecting photos only to find out they had to remove half of them.

**Comment by mjrehder** [comment]
I agree, that this solution is not optimal. We are using a limit of 1 right now and will extend that number in the future. With the limit of 1, there has already been a comment, that the Done button should not show a selected indicator and when the user selects another image, then the first picked should automatically be deselected. In the case of a single image limit, this sounds right, but the behaviour with 2+ select-able images would then have to be different.
Another solution could be to show an extra information, that specifies the limit, if such one is set. I just don't like that. It would only benefit novice users of the App and use up real estate for advanced user.
As you have observed, the solution of rejecting images after the picking, if too many has been selected, is a very bad user experience.
The only "solution" that comes to my mind right now, is to grey-out the not-selected images when the limit has been reached. This should indicate for the user that he cannot select more. You could furthermore add some unobtrusive information to the user, if he tries to tap on a greyed-out image informing him of the limit. This however would open a new can of worms, as I suspect that developers then would like to be able to customize that information.

**Comment by davbeck** [comment]
See https://github.com/davbeck/TNKImagePickerController/releases/tag/3.2.0 for an alternative to this.

**Comment by davbeck** [comment]
See https://github.com/davbeck/TNKImagePickerController/releases/tag/3.2.0 for an alternative to this.

**Pull request closed without merging**
